version: 2.1
orbs:
  node: circleci/node@4.7.0
jobs:
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - node/install-packages:
          app-dir: ./ 
          pkg-manager: yarn 
          override-ci-command: yarn 
      - run: yarn test:coverage
workflows:
  test:
    jobs:
      - test