version: 2.1
orbs:
  node: circleci/node@4.7.0
  
workflows:
    test:
      jobs:
        - node/test:
            pkg-manager: yarn 
            run-command: test:coverage 
            version: '14.17.6' 
